alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .10='cd ../../../../../../../../../..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../..'
alias .5='cd ../../../..'
alias .6='cd ../../../../../..'
alias .7='cd ../../../../../../..'
alias .8='cd ../../../../../../../..'
alias .9='cd ../../../../../../../../..'
alias _cnf_print='echo -e 1>&2'
alias add='git add'
alias add-all='git add -A'
alias amend='git commit -s --amend --no-edit'
alias amend-all='git commit -as --amend --no-edit'
alias apt='man pacman'
alias apt-get='man pacman'
alias big='expac -H M '\''%m\t%n'\'' | sort -h | nl'
alias blame='git blame'
alias branch='git branch'
alias branchs='git branch --all'
alias cat='bat -pp'
alias cd..='cd ..'
alias checkout='git checkout'
alias clean='git clean -fd'
alias cleanup='sudo pacman -Rns `pacman -Qtdq`'
alias clone='git clone'
alias commit='git commit -sm'
alias commit-all='git commit -asm'
alias commit-amend-msg='git commit --amend -sm'
alias compose=podman-compose
alias containers='podman ps -a'
alias count-git-pkg='pacman -Q | grep -i "\-git" | wc -l'
alias curl='openssl1.1 curl'
alias delete='git rm'
alias df=duf
alias dir='dir --color=auto'
alias dotgit='git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
alias down='compose down'
alias du=dust
alias edit-in-kitty='kitten edit-in-kitty'
alias egrep='grep -E --color=auto'
alias fetch='git fetch'
alias fgrep='grep -F --color=auto'
alias fix-pacman='sudo rm /var/lib/pacman/db.lck'
alias folders='exa --tree -s type --only-dirs -L'
alias follow='git log --follow --oneline --decorate'
alias forget='git rm --cached'
alias ftp-vpc='lftp alsan:Annotate2-Elastic-Example@144.34.161.226:11021'
alias full-history='history 1'
alias get-files='tmsu files'
alias get-running-services='sctl --type=service --state=running'
alias get-running-user-services='uctl --type=service --state=running'
alias get-sys-failed='systemctl list-utils --failed'
alias get-tags='tmsu tags'
alias get-untagged='tmsu untagged'
alias get-values='tmsu values'
alias git='OPENSSL_CONF=~/.config/openssl.cnf git'
alias go='gg go'
alias grep='grep --color=auto'
alias grubup='sudo update-grub'
alias helpme='cht.sh --shell'
alias hw='hwinfo --short'
alias icat='kitty +kitten icat'
alias icebox-activate='adb shell sh /sdcard/Android/data/com.catchingnow.icebox/files/start.shi'
alias ignore='curl -L -s https://www.gitignore.io/api/ >> .gitignore'
alias ignore-file='echo  >> .gitignore'
alias images='podman images'
alias inst-pkg='paru -S'
alias inst-pkg-no-deps='paru -Sdd'
alias jctl='journalctl -p 3 -xb'
alias l=ls
alias l.='exa -l --color always --icons -a -H -s type | egrep "^\."'
alias lS='exa -1'
alias la='ls -lbhHigUmuSa'
alias lsd='ls -d */'
alias less=bat
alias lfs='git lfs'
alias ll='ls -la'
alias llm='ll --sort=modified'
alias log='git --no-pager log --oneline --decorate'
alias logg='git log --graph --all --oneline --decorate'
alias logs='git log --graph --pretty=format:"%Cblue%h%Creset -%C(yellow)%d%Creset %s%Cgreen(%cr) %C(bold blue)%Creset"'
alias ls='exa -G --icons --group-directories-first'
alias ls-files='git ls-files'
alias lx='ls -lbhHigUmuSa@'
alias mdcat='mdcat -p'
alias merge='git merge'
alias mergetool='git mergetool'
alias mirror='sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist'
alias mirrora='sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist'
alias mirrord='sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist'
alias mirrors='sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist'
alias mkdir='mkdir -pv'
alias mount-disk=udiskie-mount
alias open=xdg-open
alias openssl1.1='OPENSSL_CONF=~/.config/openssl.cnf'
alias pacdiff='sudo -H DIFFPROG=meld pacdiff'
alias pacs='pacman -Slq | fzf --multi --preview '\''pacpreview {1}'\'' | xargs -ro sudo pacman -S'
alias ping=prettyping
alias prune='git fetch --prune'
alias pull='git pull --rebase=merges'
alias push='git pull --rebase=merges && git push'
alias rebase='git rebase'
alias reflog='git reflog'
alias remote='git remote'
alias reset='git reset --hard'
alias resolve='git mergetool'
alias revert='git revert'
alias rg='rg -uuu'
alias rip='expac --timefmt='\''%Y-%m-%d %T'\'' '\''%l\t%n %v'\'' | sort | tail -200 | nl'
alias rm-dangling='podman rmi $(podman images -f "dangling=true" -q)'
alias rmi='podman rmi'
alias rmpkg='sudo pacman -Rdd'
alias run-help=man
alias sctl='sudo systemctl'
alias set-mine='sudo chown -R $(whoami):$(whoami)'
alias set-ours='git pull -s recursive -X ours'
alias set-proxy='http_proxy=socks5h://127.0.0.1:1080 https_proxy=socks5h://127.0.0.1:1080'
alias set-theirs='git pull -s recursive -X theirs'
alias setclip='xclip -selection c'
alias shortlog='git --no-pager shortlog -sn'
alias show='git show'
alias side-by-side='sed '\''s/    //g'\'' | cut -d'\''/'\'' -f2 | sed '\''N;s/\n/|/'\'' | sort | column -s'\''|'\'' -t'
alias ssh='TERM=xterm-256color ssh -4'
alias start='sudo systemctl start'
alias stash='git stash'
alias stash-all='git save --include-untracked'
alias stderred='LD_PRELOAD=/usr/lib/libstderred.so${LD_PRELOAD:+:$LD_PRELOAD}'
alias stop='sudo systemctl stop'
alias tag='tmsu tag'
alias tag-files='fd -x tmsu tags {}'
alias tb='nc termbin.com 9999'
alias to-null='2>/dev/null'
alias to-stderr='>&2'
alias top10='head -10'
alias track='git lfs track'
alias tree='exa --tree -L'
alias uctl='systemctl --user'
alias umount-disk=udiskie-umount
alias undo='reset --soft HEAD ^'
alias unlock-pacman='sudo rm /var/lib/pacman/db.lck'
alias untag='tmsu untag '
alias up='compose up -d'
alias upd=/usr/bin/update
alias update='paru -Sy'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias upgrade='paru -Su'
alias vdir='vdir --color=auto'
alias virsh='virsh -c qemu:///system'
alias wget='wget -c '
alias what-changed='git whatchanged'
alias which=whence
alias which-command=whence
